"""Tests for the Phase IV correspondence / rotation-recovery module.

These tests are deterministic and synthetic. They validate ``correspondence.py``
behaviour on controlled pairs generated by ``paired.py``: circular statistics,
coarse cyclic matching, sub-lattice NCC refinement, rotation/scale estimation,
quality gates (NCC, residual consensus, ambiguity, descriptor similarity,
degeneracy), estimator robustness, and determinism. Rotations follow the
documented sign convention: a positive rotation (clockwise on screen) of the
IMAGE yields a positive rotation estimate, and an estimate of ``357`` is
reported for a ``-3`` rotation.
"""

import numpy as np
import pytest

from pupil_tracking.iris.correspondence import (
    FailureKind,
    MatchingBaseline,
    Correspondence,
    CorrespondenceConfig,
    _estimate_consensus,
    _estimate_ransac_exhaustive,
    _estimate_weighted_circular,
    angular_span,
    circular_distance,
    circular_mean,
    circular_signed_difference,
    circular_std,
    descriptor_distance,
    descriptor_similarity,
    estimate_correspondence,
    evaluate_pair,
    wrap_deg,
)
from pupil_tracking.iris.detect import detect_iris_features
from pupil_tracking.iris.paired import PairConfig, make_synthetic_pair
from pupil_tracking.iris.types import IrisFeature, IrisFeatureSet, IrisROI
from pupil_tracking.utils.types import EllipseParams


# ── fixtures ───────────────────────────────────────────────────────────

def _synthetic_iris_bgr(size=320, rng_seed=7, texture=12.0):
    """Synthetic textured 'iris' test image (BGR), deterministic per seed."""
    yy, xx = np.mgrid[0:size, 0:size]
    rad = np.sqrt((xx - size / 2.0) ** 2 + (yy - size / 2.0) ** 2)
    iris = (60 + 120 * (np.sin(rad * 0.5))).clip(0, 255).astype(np.uint8)
    rng = np.random.default_rng(rng_seed)
    noise = rng.integers(-int(texture), int(texture), iris.shape).astype(np.int16)
    gray = np.clip(iris.astype(np.int16) + noise, 0, 255).astype(np.uint8)
    return np.stack([gray, gray, gray], axis=-1)


@pytest.fixture(scope="module")
def eye_src():
    return _synthetic_iris_bgr()


@pytest.fixture(scope="module")
def eye_geo():
    size = 320
    c = size // 2
    return (EllipseParams(center_x=c, center_y=c, semi_major=55.0,
                          semi_minor=55.0, angle_deg=0.0),
            EllipseParams(center_x=c, center_y=c, semi_major=130.0,
                          semi_minor=130.0, angle_deg=0.0))


@pytest.fixture(scope="module")
def feats_a(eye_src, eye_geo):
    pe, le = eye_geo
    res = detect_iris_features(eye_src, pe, le)
    assert res.feature_set.roi.valid
    return res.feature_set


def _feats_b(eye_src, eye_geo, config, *, ellipse_scale=1.0):
    pe, le = eye_geo
    pair = make_synthetic_pair(eye_src, config)
    c = eye_src.shape[0] / 2.0
    pe_b = EllipseParams(center_x=c, center_y=c, semi_major=55.0 * ellipse_scale,
                         semi_minor=55.0 * ellipse_scale, angle_deg=0.0)
    le_b = EllipseParams(center_x=c, center_y=c, semi_major=130.0 * ellipse_scale,
                         semi_minor=130.0 * ellipse_scale, angle_deg=0.0)
    res = detect_iris_features(pair.image_b, pe_b, le_b)
    return pair, res.feature_set


def _build_pair(eye_src, eye_geo, feats_a, config, ellipse_scale=1.0):
    pair, feats_b = _feats_b(eye_src, eye_geo, config,
                             ellipse_scale=ellipse_scale)
    best = f"rot={config.rotation_deg}"
    out = evaluate_pair(
        eye_src, pair.image_b, feats_a, feats_b,
        gt_rotation_deg=float(config.rotation_deg),
        gt_scale=float(config.scale),
    )
    return out


# ── circular statistics / descriptors ──────────────────────────────────

def test_min_circular_difference_metric_wraps_correctly():
    assert circular_distance(350.0, 10.0) == pytest.approx(20.0)
    assert circular_distance(10.0, 350.0) == pytest.approx(20.0)
    assert circular_distance(0.0, 360.0) == pytest.approx(0.0)
    assert circular_distance(180.0, 0.0) == pytest.approx(180.0)
    assert circular_distance(350.0, 359.0) == pytest.approx(9.0)
    assert circular_distance(90.0, 90.0) == pytest.approx(0.0)
    assert circular_signed_difference(0.0, 355.0) == pytest.approx(-5.0)
    assert circular_signed_difference(0.0, 5.0) == pytest.approx(5.0)


def test_circular_statistics_mean_std_span():
    assert wrap_deg(-5.0) == pytest.approx(355.0)
    assert circular_mean([0.0, 10.0]) == pytest.approx(5.0)
    assert circular_distance(circular_mean([350.0, 10.0]), 0.0) <= 1e-9
    assert circular_mean([10.0, 20.0], [1.0, 3.0]) == pytest.approx(17.5, abs=0.1)
    assert circular_std([10.0, 10.0]) == pytest.approx(0.0)
    assert circular_std([0.0, 90.0]) > 40.0
    assert angular_span([10.0, 20.0, 30.0]) == pytest.approx(20.0)
    assert angular_span([0.0, 359.0]) == pytest.approx(1.0)


def test_descriptor_distance_and_similarity():
    a = np.zeros(16, dtype=np.float32)
    b = np.zeros(16, dtype=np.float32)
    a[0], b[3] = 1.0, 1.0
    ident = np.zeros(16, dtype=np.float32)
    ident[4] = 1.0
    assert descriptor_distance(a, a) == pytest.approx(0.0)
    assert descriptor_distance(a, b) == pytest.approx(2.0)
    assert descriptor_similarity(a, a) == pytest.approx(1.0)
    assert descriptor_similarity(a, b) < 1.0
    # missing descriptor is neutral, not penalised
    assert descriptor_distance(None, a) is None
    assert descriptor_similarity(None, a) == pytest.approx(1.0)


# ── rotation recovery (sign convention checkpoint) ─────────────────────

def test_identity_pair_estimate_zero_rotation(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=0.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    assert out["success_0_5_deg"] is True


def test_rotation_plus_1_deg(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=1.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    # positive rotation => positive estimate, not ~359
    assert abs(out["estimated_rotation_deg"] - 1.0) <= 0.5


def test_rotation_minus_1_deg(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=-1.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    # negative rotation => estimate near 359, not near +359... i.e. near -1
    assert out["estimated_rotation_deg"] > 358.0


def test_rotation_plus_3_deg_sublattice(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=3.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    assert abs(out["rotation_error_signed_deg"]) <= 0.5


def test_rotation_minus_3_deg_sublattice(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=-3.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    assert abs(out["estimated_rotation_deg"] - 357.0) <= 0.5


def test_lattice_multiple_rotation_5_deg(eye_src, eye_geo, feats_a):
    # A lattice-multiple rotation (5 deg) is recovered to sub-0.5 deg. On the
    # rotationally smooth synthetic texture the coarse lattice search is
    # degenerate (every alignment is geometrically plausible), so the heavy
    # lifting happens in the sub-lattice NCC refinement -- that is exactly the
    # path this case pins down.
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=5.0))
    assert out["failure"] == "OK"
    assert out["refined_used"] > 0
    assert out["min_circular_diff_deg"] <= 0.5


def test_rotation_359_deg_wraparound(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=359.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5


# ── scale recovery and matching refusal ────────────────────────────────

def test_scale_only_has_no_rotation_bias(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a,
                      PairConfig(rotation_deg=0.0, scale=1.05),
                      ellipse_scale=1.05)
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    assert out["scale_error_ratio"] == pytest.approx(1.0, abs=0.02)


def test_rotation_plus_scale_combined(eye_src, eye_geo, feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a,
                      PairConfig(rotation_deg=3.0, scale=1.03),
                      ellipse_scale=1.03)
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5
    assert out["scale_error_ratio"] == pytest.approx(1.0, abs=0.02)


def test_content_mismatch_rejected_as_low_ncc(eye_src, eye_geo, feats_a):
    # IMAGE B is a different texture entirely: refinement NCC gates it.
    pe, le = eye_geo
    other = detect_iris_features(_synthetic_iris_bgr(rng_seed=99), pe, le)
    out = evaluate_pair(eye_src, _synthetic_iris_bgr(rng_seed=99),
                        feats_a, other.feature_set, gt_rotation_deg=0.0,
                        gt_scale=1.0)
    assert out["failure"] != "OK"
    assert out["failure"] in (FailureKind.LOW_NCC.value,
                              FailureKind.HIGH_RESIDUAL.value)


def test_translation_only_pair_never_misreported_as_rotation(eye_src, eye_geo,
                                                            feats_a):
    out = _build_pair(eye_src, eye_geo, feats_a,
                      PairConfig(translation_px=(4, 0)))
    # A lateral shift is NOT a rotation: honest rejection is mandatory;
    # a "rotation" of ~357/0 with OK is not acceptable.
    assert out["failure"] != "OK"


# ── estimator robustness ───────────────────────────────────────────────

def test_estimators_agree_on_clean_pair(eye_src, eye_geo, feats_a):
    pair, feats_b = _feats_b(eye_src, eye_geo,
                             PairConfig(rotation_deg=3.0))
    res = estimate_correspondence(eye_src, pair.image_b, feats_a, feats_b)
    vals = list(res.rotation_estimates.values())
    assert abs(vals[0] - vals[1]) <= 0.3
    assert abs(vals[0] - vals[2]) <= 0.3
    assert circular_distance(res.estimated_rotation_deg, 3.0) <= 0.5


def test_outlier_angles_do_not_break_estimators():
    thetas = np.asarray([3.0, 3.0, 3.0, 3.0, 3.0, 170.0, 250.0, 100.0])
    weights = np.ones_like(thetas)
    cfg = CorrespondenceConfig()
    consensus = _estimate_consensus(thetas, weights)
    ransac = _estimate_ransac_exhaustive(thetas, weights, cfg.ransac_tol_deg)
    assert circular_distance(consensus, 3.0) <= 0.5
    assert circular_distance(ransac, 3.0) <= 0.5
    # weighted circular mean is sensitive to outliers: it must NOT match the
    # robust estimates here (documents the reason consensus is the default).
    weighted = _estimate_weighted_circular(thetas, weights)
    assert circular_distance(weighted, consensus) > 3.0


# ── quality gates / degenerate & ambiguous paths ───────────────────────

def _mini_roi():
    return IrisROI(valid=True, center_x=160.0, center_y=160.0,
                   pupil_radius_px=55.0, limbus_radius_px=130.0)


def _mini_feature(angle_deg, desc_bin, conf=0.9):
    desc = np.zeros(16, dtype=np.float32)
    desc[desc_bin % 16] = 1.0
    return IrisFeature(angle_deg=float(angle_deg), radial_norm=0.5,
                       x=0.0, y=0.0, confidence=conf, descriptor=desc)


def _mini_fset(features):
    s = IrisFeatureSet(roi=_mini_roi(), features=list(features))
    return s


def test_too_few_matches_reports_degeneracy():
    cfg = CorrespondenceConfig(refine=False)
    feats_a = _mini_fset([_mini_feature(10.0, 0), _mini_feature(200.0, 1)])
    feats_b = _mini_fset([_mini_feature(10.0, 0), _mini_feature(200.0, 1)])
    blank = np.zeros((320, 320, 3), dtype=np.uint8)
    res = estimate_correspondence(blank, blank, feats_a, feats_b, config=cfg)
    assert res.failure == FailureKind.DEGENERATE
    assert res.valid is False
    assert res.n_matches < cfg.min_matches


def test_ambiguous_pair_flagged_low_ambiguity_sparse_ok():
    cfg = CorrespondenceConfig(refine=False)
    blank = np.zeros((320, 320, 3), dtype=np.uint8)
    # dense A and B grids: several A features race for each B in the corridors
    dense_a = _mini_fset([_mini_feature(a, int(4 * a)) for a in (0.0, 0.5, 1.0, 1.5)])
    dense_b = _mini_fset([_mini_feature(a, int(4 * a)) for a in (0.2, 0.7, 1.2, 1.7)])
    res_dense = estimate_correspondence(blank, blank, dense_a, dense_b, config=cfg)
    assert res_dense.failure == FailureKind.AMBIGUOUS
    assert res_dense.ambiguity_ratio > cfg.ambiguity_ratio_max
    # well-separated control has no ambiguity
    sparse_a = _mini_fset([_mini_feature(a, int(a)) for a in (0.0, 30.0, 60.0, 90.0)])
    sparse_b = _mini_fset([_mini_feature(a, int(a)) for a in (0.0, 30.0, 60.0, 90.0)])
    res_sparse = estimate_correspondence(blank, blank, sparse_a, sparse_b, config=cfg)
    assert res_sparse.ambiguity_ratio == pytest.approx(0.0)


def test_low_descriptor_similarity_rejected():
    cfg = CorrespondenceConfig(refine=False)
    blank = np.zeros((320, 320, 3), dtype=np.uint8)
    angles = (0.0, 30.0, 60.0, 90.0)
    feats_a = _mini_fset([_mini_feature(a, i) for i, a in enumerate(angles)])
    feats_b = _mini_fset([_mini_feature(a, 10 + i) for i, a in enumerate(angles)])
    res = estimate_correspondence(blank, blank, feats_a, feats_b, config=cfg)
    assert res.failure == FailureKind.LOW_SIMILARITY
    assert res.valid is False


def test_matching_is_one_to_one_and_deterministic(eye_src, eye_geo, feats_a):
    cfg = CorrespondenceConfig(refine=False)
    pair, feats_b = _feats_b(eye_src, eye_geo, PairConfig(rotation_deg=3.0))
    r1 = estimate_correspondence(eye_src, pair.image_b, feats_a, feats_b,
                                 config=cfg)
    r2 = estimate_correspondence(eye_src, pair.image_b, feats_a, feats_b,
                                 config=cfg)
    pairs1 = [(m.index_a, m.index_b) for m in r1.matched]
    pairs2 = [(m.index_a, m.index_b) for m in r2.matched]
    assert pairs1 == pairs2
    assert len(pairs1) == len(set(pairs1))
    b_ids = [ib for _, ib in pairs1]
    assert len(b_ids) == len(set(b_ids)), "each IMAGE-B feature matched at most once"


# ── nuisance perturbations on top of a rotation ────────────────────────

def test_reflection_and_occlusion_perturbed_pairs_deterministic(eye_src, eye_geo,
                                                               feats_a):
    for kind in ("reflection", "occlusion"):
        pair, feats_b = _feats_b(eye_src, eye_geo, PairConfig(
            rotation_deg=3.0, perturbation=kind, seed=5))
        o1 = estimate_correspondence(eye_src, pair.image_b, feats_a, feats_b)
        pair2, feats_b2 = _feats_b(eye_src, eye_geo, PairConfig(
            rotation_deg=3.0, perturbation=kind, seed=5))
        o2 = estimate_correspondence(eye_src, pair2.image_b, feats_a, feats_b2)
        assert o1.estimated_rotation_deg == o2.estimated_rotation_deg
        assert o1.failure == o2.failure
        # Either the rotation is recovered cleanly, or the pair is rejected
        # explicitly -- never a confident wrong-rotation OK.
        if o1.failure == FailureKind.OK:
            assert circular_distance(o1.estimated_rotation_deg, 3.0) <= 0.5


# ── Phase VIII-B: NCC flat-peak gate regression tests ──────────────────

def test_coarse_basin_negative_rotation(eye_src, eye_geo, feats_a):
    """Correct coarse + negative rotation: coarse basin centres the search."""
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=-5.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 1.0
    assert abs(out["estimated_rotation_deg"] - 355.0) <= 1.0


def test_coarse_basin_positive_rotation(eye_src, eye_geo, feats_a):
    """Correct coarse + positive lattice rotation: NCC refines around basin."""
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=5.0))
    assert out["failure"] == "OK"
    assert out["refined_used"] > 0
    assert out["min_circular_diff_deg"] <= 0.5


def test_wraparound_359_deg_coarse_basin(eye_src, eye_geo, feats_a):
    """359 deg wraps to -1: coarse basin must handle circular boundary."""
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=359.0))
    assert out["failure"] == "OK"
    assert out["min_circular_diff_deg"] <= 0.5


def test_subdegree_ncc_correction_preserved(eye_src, eye_geo, feats_a):
    """Small legitimate sub-degree NCC correction is not suppressed."""
    out = _build_pair(eye_src, eye_geo, feats_a, PairConfig(rotation_deg=0.5))
    assert out["failure"] == "OK"
    assert out["refined_used"] > 0
    assert out["min_circular_diff_deg"] <= 0.5


def test_weak_ncc_preserves_coarse_basin(eye_src, eye_geo, feats_a):
    """When NCC evidence is weak (content mismatch), the coarse basin is
    not forced to produce an OK result -- honest rejection is expected."""
    pe, le = eye_geo
    other = detect_iris_features(_synthetic_iris_bgr(rng_seed=99), pe, le)
    out = evaluate_pair(eye_src, _synthetic_iris_bgr(rng_seed=99),
                        feats_a, other.feature_set, gt_rotation_deg=0.0,
                        gt_scale=1.0)
    assert out["failure"] != "OK"


def test_ncc_refinement_deterministic(eye_src, eye_geo, feats_a):
    """Repeated identical pair yields identical rotation estimate."""
    config = PairConfig(rotation_deg=3.0)
    pair1, fb1 = _feats_b(eye_src, eye_geo, config)
    r1 = estimate_correspondence(eye_src, pair1.image_b, feats_a, fb1)
    pair2, fb2 = _feats_b(eye_src, eye_geo, config)
    r2 = estimate_correspondence(eye_src, pair2.image_b, feats_a, fb2)
    assert r1.estimated_rotation_deg == r2.estimated_rotation_deg
    assert r1.failure == r2.failure
    assert r1.refined_used == r2.refined_used